language: java
sudo: false
dist: xenial
script: ./mvnw -V clean verify --fail-at-end -U -Prelease-checks
matrix:
  include:
    - jdk: openjdk8
      env: JACOCO=true COVERALLS=true
    - jdk: openjdk11
      env: JACOCO=true
    - jdk: openjdk8
      env: JACOCO=true SONAR=publish
notifications:
  email:
    on_failure: change
