language: java
script: ./mvnw install --fail-at-end
matrix:
  include:
  - jdk: openjdk7
    env: JACOCO=true COVERALLS=true
  - jdk: openjdk8
    env: JACOCO=true COVERALLS=true
  - jdk: oraclejdk8
    env: JACOCO=false COVERALLS=true
  - jdk: oraclejdk9
    env: JACOCO=true COVERALLS=true
  - jdk: openjdk8
    env: GDMSESSION=sonar
  - jdk: openjdk8
    env: SONAR=publish
